on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: WillAbides/setup-go-faster@v1.5.0
        id: setup-go-faster
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        if: ${{ runner.os == 'Linux' }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
